// jsv_sdram_mm_interconnect_0.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 19.1 670

`timescale 1 ps / 1 ps
module jsv_sdram_mm_interconnect_0 (
		input  wire        clk_0_clk_clk,                                  //                                clk_0_clk.clk
		input  wire        sdram_pll_c0_clk,                               //                             sdram_pll_c0.clk
		input  wire        bitmap_sdram_reset_reset_bridge_in_reset_reset, // bitmap_sdram_reset_reset_bridge_in_reset.reset
		input  wire        bridge_0_reset_reset_bridge_in_reset_reset,     //     bridge_0_reset_reset_bridge_in_reset.reset
		input  wire [22:0] bridge_0_avalon_master_address,                 //                   bridge_0_avalon_master.address
		output wire        bridge_0_avalon_master_waitrequest,             //                                         .waitrequest
		input  wire [1:0]  bridge_0_avalon_master_byteenable,              //                                         .byteenable
		input  wire        bridge_0_avalon_master_read,                    //                                         .read
		output wire [15:0] bridge_0_avalon_master_readdata,                //                                         .readdata
		input  wire        bridge_0_avalon_master_write,                   //                                         .write
		input  wire [15:0] bridge_0_avalon_master_writedata,               //                                         .writedata
		output wire [20:0] bitmap_sdram_s1_address,                        //                          bitmap_sdram_s1.address
		output wire        bitmap_sdram_s1_write,                          //                                         .write
		output wire        bitmap_sdram_s1_read,                           //                                         .read
		input  wire [15:0] bitmap_sdram_s1_readdata,                       //                                         .readdata
		output wire [15:0] bitmap_sdram_s1_writedata,                      //                                         .writedata
		output wire [1:0]  bitmap_sdram_s1_byteenable,                     //                                         .byteenable
		input  wire        bitmap_sdram_s1_readdatavalid,                  //                                         .readdatavalid
		input  wire        bitmap_sdram_s1_waitrequest,                    //                                         .waitrequest
		output wire        bitmap_sdram_s1_chipselect,                     //                                         .chipselect
		output wire [1:0]  sdram_pll_pll_slave_address,                    //                      sdram_pll_pll_slave.address
		output wire        sdram_pll_pll_slave_write,                      //                                         .write
		output wire        sdram_pll_pll_slave_read,                       //                                         .read
		input  wire [31:0] sdram_pll_pll_slave_readdata,                   //                                         .readdata
		output wire [31:0] sdram_pll_pll_slave_writedata                   //                                         .writedata
	);

	wire         bridge_0_avalon_master_translator_avalon_universal_master_0_waitrequest;   // bridge_0_avalon_master_agent:av_waitrequest -> bridge_0_avalon_master_translator:uav_waitrequest
	wire  [15:0] bridge_0_avalon_master_translator_avalon_universal_master_0_readdata;      // bridge_0_avalon_master_agent:av_readdata -> bridge_0_avalon_master_translator:uav_readdata
	wire         bridge_0_avalon_master_translator_avalon_universal_master_0_debugaccess;   // bridge_0_avalon_master_translator:uav_debugaccess -> bridge_0_avalon_master_agent:av_debugaccess
	wire  [22:0] bridge_0_avalon_master_translator_avalon_universal_master_0_address;       // bridge_0_avalon_master_translator:uav_address -> bridge_0_avalon_master_agent:av_address
	wire         bridge_0_avalon_master_translator_avalon_universal_master_0_read;          // bridge_0_avalon_master_translator:uav_read -> bridge_0_avalon_master_agent:av_read
	wire   [1:0] bridge_0_avalon_master_translator_avalon_universal_master_0_byteenable;    // bridge_0_avalon_master_translator:uav_byteenable -> bridge_0_avalon_master_agent:av_byteenable
	wire         bridge_0_avalon_master_translator_avalon_universal_master_0_readdatavalid; // bridge_0_avalon_master_agent:av_readdatavalid -> bridge_0_avalon_master_translator:uav_readdatavalid
	wire         bridge_0_avalon_master_translator_avalon_universal_master_0_lock;          // bridge_0_avalon_master_translator:uav_lock -> bridge_0_avalon_master_agent:av_lock
	wire         bridge_0_avalon_master_translator_avalon_universal_master_0_write;         // bridge_0_avalon_master_translator:uav_write -> bridge_0_avalon_master_agent:av_write
	wire  [15:0] bridge_0_avalon_master_translator_avalon_universal_master_0_writedata;     // bridge_0_avalon_master_translator:uav_writedata -> bridge_0_avalon_master_agent:av_writedata
	wire   [1:0] bridge_0_avalon_master_translator_avalon_universal_master_0_burstcount;    // bridge_0_avalon_master_translator:uav_burstcount -> bridge_0_avalon_master_agent:av_burstcount
	wire         rsp_mux_src_valid;                                                         // rsp_mux:src_valid -> bridge_0_avalon_master_agent:rp_valid
	wire  [74:0] rsp_mux_src_data;                                                          // rsp_mux:src_data -> bridge_0_avalon_master_agent:rp_data
	wire         rsp_mux_src_ready;                                                         // bridge_0_avalon_master_agent:rp_ready -> rsp_mux:src_ready
	wire   [1:0] rsp_mux_src_channel;                                                       // rsp_mux:src_channel -> bridge_0_avalon_master_agent:rp_channel
	wire         rsp_mux_src_startofpacket;                                                 // rsp_mux:src_startofpacket -> bridge_0_avalon_master_agent:rp_startofpacket
	wire         rsp_mux_src_endofpacket;                                                   // rsp_mux:src_endofpacket -> bridge_0_avalon_master_agent:rp_endofpacket
	wire  [31:0] sdram_pll_pll_slave_agent_m0_readdata;                                     // sdram_pll_pll_slave_translator:uav_readdata -> sdram_pll_pll_slave_agent:m0_readdata
	wire         sdram_pll_pll_slave_agent_m0_waitrequest;                                  // sdram_pll_pll_slave_translator:uav_waitrequest -> sdram_pll_pll_slave_agent:m0_waitrequest
	wire         sdram_pll_pll_slave_agent_m0_debugaccess;                                  // sdram_pll_pll_slave_agent:m0_debugaccess -> sdram_pll_pll_slave_translator:uav_debugaccess
	wire  [22:0] sdram_pll_pll_slave_agent_m0_address;                                      // sdram_pll_pll_slave_agent:m0_address -> sdram_pll_pll_slave_translator:uav_address
	wire   [3:0] sdram_pll_pll_slave_agent_m0_byteenable;                                   // sdram_pll_pll_slave_agent:m0_byteenable -> sdram_pll_pll_slave_translator:uav_byteenable
	wire         sdram_pll_pll_slave_agent_m0_read;                                         // sdram_pll_pll_slave_agent:m0_read -> sdram_pll_pll_slave_translator:uav_read
	wire         sdram_pll_pll_slave_agent_m0_readdatavalid;                                // sdram_pll_pll_slave_translator:uav_readdatavalid -> sdram_pll_pll_slave_agent:m0_readdatavalid
	wire         sdram_pll_pll_slave_agent_m0_lock;                                         // sdram_pll_pll_slave_agent:m0_lock -> sdram_pll_pll_slave_translator:uav_lock
	wire  [31:0] sdram_pll_pll_slave_agent_m0_writedata;                                    // sdram_pll_pll_slave_agent:m0_writedata -> sdram_pll_pll_slave_translator:uav_writedata
	wire         sdram_pll_pll_slave_agent_m0_write;                                        // sdram_pll_pll_slave_agent:m0_write -> sdram_pll_pll_slave_translator:uav_write
	wire   [2:0] sdram_pll_pll_slave_agent_m0_burstcount;                                   // sdram_pll_pll_slave_agent:m0_burstcount -> sdram_pll_pll_slave_translator:uav_burstcount
	wire         sdram_pll_pll_slave_agent_rf_source_valid;                                 // sdram_pll_pll_slave_agent:rf_source_valid -> sdram_pll_pll_slave_agent_rsp_fifo:in_valid
	wire  [93:0] sdram_pll_pll_slave_agent_rf_source_data;                                  // sdram_pll_pll_slave_agent:rf_source_data -> sdram_pll_pll_slave_agent_rsp_fifo:in_data
	wire         sdram_pll_pll_slave_agent_rf_source_ready;                                 // sdram_pll_pll_slave_agent_rsp_fifo:in_ready -> sdram_pll_pll_slave_agent:rf_source_ready
	wire         sdram_pll_pll_slave_agent_rf_source_startofpacket;                         // sdram_pll_pll_slave_agent:rf_source_startofpacket -> sdram_pll_pll_slave_agent_rsp_fifo:in_startofpacket
	wire         sdram_pll_pll_slave_agent_rf_source_endofpacket;                           // sdram_pll_pll_slave_agent:rf_source_endofpacket -> sdram_pll_pll_slave_agent_rsp_fifo:in_endofpacket
	wire         sdram_pll_pll_slave_agent_rsp_fifo_out_valid;                              // sdram_pll_pll_slave_agent_rsp_fifo:out_valid -> sdram_pll_pll_slave_agent:rf_sink_valid
	wire  [93:0] sdram_pll_pll_slave_agent_rsp_fifo_out_data;                               // sdram_pll_pll_slave_agent_rsp_fifo:out_data -> sdram_pll_pll_slave_agent:rf_sink_data
	wire         sdram_pll_pll_slave_agent_rsp_fifo_out_ready;                              // sdram_pll_pll_slave_agent:rf_sink_ready -> sdram_pll_pll_slave_agent_rsp_fifo:out_ready
	wire         sdram_pll_pll_slave_agent_rsp_fifo_out_startofpacket;                      // sdram_pll_pll_slave_agent_rsp_fifo:out_startofpacket -> sdram_pll_pll_slave_agent:rf_sink_startofpacket
	wire         sdram_pll_pll_slave_agent_rsp_fifo_out_endofpacket;                        // sdram_pll_pll_slave_agent_rsp_fifo:out_endofpacket -> sdram_pll_pll_slave_agent:rf_sink_endofpacket
	wire  [15:0] bitmap_sdram_s1_agent_m0_readdata;                                         // bitmap_sdram_s1_translator:uav_readdata -> bitmap_sdram_s1_agent:m0_readdata
	wire         bitmap_sdram_s1_agent_m0_waitrequest;                                      // bitmap_sdram_s1_translator:uav_waitrequest -> bitmap_sdram_s1_agent:m0_waitrequest
	wire         bitmap_sdram_s1_agent_m0_debugaccess;                                      // bitmap_sdram_s1_agent:m0_debugaccess -> bitmap_sdram_s1_translator:uav_debugaccess
	wire  [22:0] bitmap_sdram_s1_agent_m0_address;                                          // bitmap_sdram_s1_agent:m0_address -> bitmap_sdram_s1_translator:uav_address
	wire   [1:0] bitmap_sdram_s1_agent_m0_byteenable;                                       // bitmap_sdram_s1_agent:m0_byteenable -> bitmap_sdram_s1_translator:uav_byteenable
	wire         bitmap_sdram_s1_agent_m0_read;                                             // bitmap_sdram_s1_agent:m0_read -> bitmap_sdram_s1_translator:uav_read
	wire         bitmap_sdram_s1_agent_m0_readdatavalid;                                    // bitmap_sdram_s1_translator:uav_readdatavalid -> bitmap_sdram_s1_agent:m0_readdatavalid
	wire         bitmap_sdram_s1_agent_m0_lock;                                             // bitmap_sdram_s1_agent:m0_lock -> bitmap_sdram_s1_translator:uav_lock
	wire  [15:0] bitmap_sdram_s1_agent_m0_writedata;                                        // bitmap_sdram_s1_agent:m0_writedata -> bitmap_sdram_s1_translator:uav_writedata
	wire         bitmap_sdram_s1_agent_m0_write;                                            // bitmap_sdram_s1_agent:m0_write -> bitmap_sdram_s1_translator:uav_write
	wire   [1:0] bitmap_sdram_s1_agent_m0_burstcount;                                       // bitmap_sdram_s1_agent:m0_burstcount -> bitmap_sdram_s1_translator:uav_burstcount
	wire         bitmap_sdram_s1_agent_rf_source_valid;                                     // bitmap_sdram_s1_agent:rf_source_valid -> bitmap_sdram_s1_agent_rsp_fifo:in_valid
	wire  [75:0] bitmap_sdram_s1_agent_rf_source_data;                                      // bitmap_sdram_s1_agent:rf_source_data -> bitmap_sdram_s1_agent_rsp_fifo:in_data
	wire         bitmap_sdram_s1_agent_rf_source_ready;                                     // bitmap_sdram_s1_agent_rsp_fifo:in_ready -> bitmap_sdram_s1_agent:rf_source_ready
	wire         bitmap_sdram_s1_agent_rf_source_startofpacket;                             // bitmap_sdram_s1_agent:rf_source_startofpacket -> bitmap_sdram_s1_agent_rsp_fifo:in_startofpacket
	wire         bitmap_sdram_s1_agent_rf_source_endofpacket;                               // bitmap_sdram_s1_agent:rf_source_endofpacket -> bitmap_sdram_s1_agent_rsp_fifo:in_endofpacket
	wire         bitmap_sdram_s1_agent_rsp_fifo_out_valid;                                  // bitmap_sdram_s1_agent_rsp_fifo:out_valid -> bitmap_sdram_s1_agent:rf_sink_valid
	wire  [75:0] bitmap_sdram_s1_agent_rsp_fifo_out_data;                                   // bitmap_sdram_s1_agent_rsp_fifo:out_data -> bitmap_sdram_s1_agent:rf_sink_data
	wire         bitmap_sdram_s1_agent_rsp_fifo_out_ready;                                  // bitmap_sdram_s1_agent:rf_sink_ready -> bitmap_sdram_s1_agent_rsp_fifo:out_ready
	wire         bitmap_sdram_s1_agent_rsp_fifo_out_startofpacket;                          // bitmap_sdram_s1_agent_rsp_fifo:out_startofpacket -> bitmap_sdram_s1_agent:rf_sink_startofpacket
	wire         bitmap_sdram_s1_agent_rsp_fifo_out_endofpacket;                            // bitmap_sdram_s1_agent_rsp_fifo:out_endofpacket -> bitmap_sdram_s1_agent:rf_sink_endofpacket
	wire         bitmap_sdram_s1_agent_rdata_fifo_src_valid;                                // bitmap_sdram_s1_agent:rdata_fifo_src_valid -> bitmap_sdram_s1_agent_rdata_fifo:in_valid
	wire  [17:0] bitmap_sdram_s1_agent_rdata_fifo_src_data;                                 // bitmap_sdram_s1_agent:rdata_fifo_src_data -> bitmap_sdram_s1_agent_rdata_fifo:in_data
	wire         bitmap_sdram_s1_agent_rdata_fifo_src_ready;                                // bitmap_sdram_s1_agent_rdata_fifo:in_ready -> bitmap_sdram_s1_agent:rdata_fifo_src_ready
	wire         cmd_mux_001_src_valid;                                                     // cmd_mux_001:src_valid -> bitmap_sdram_s1_agent:cp_valid
	wire  [74:0] cmd_mux_001_src_data;                                                      // cmd_mux_001:src_data -> bitmap_sdram_s1_agent:cp_data
	wire         cmd_mux_001_src_ready;                                                     // bitmap_sdram_s1_agent:cp_ready -> cmd_mux_001:src_ready
	wire   [1:0] cmd_mux_001_src_channel;                                                   // cmd_mux_001:src_channel -> bitmap_sdram_s1_agent:cp_channel
	wire         cmd_mux_001_src_startofpacket;                                             // cmd_mux_001:src_startofpacket -> bitmap_sdram_s1_agent:cp_startofpacket
	wire         cmd_mux_001_src_endofpacket;                                               // cmd_mux_001:src_endofpacket -> bitmap_sdram_s1_agent:cp_endofpacket
	wire         bridge_0_avalon_master_agent_cp_valid;                                     // bridge_0_avalon_master_agent:cp_valid -> router:sink_valid
	wire  [74:0] bridge_0_avalon_master_agent_cp_data;                                      // bridge_0_avalon_master_agent:cp_data -> router:sink_data
	wire         bridge_0_avalon_master_agent_cp_ready;                                     // router:sink_ready -> bridge_0_avalon_master_agent:cp_ready
	wire         bridge_0_avalon_master_agent_cp_startofpacket;                             // bridge_0_avalon_master_agent:cp_startofpacket -> router:sink_startofpacket
	wire         bridge_0_avalon_master_agent_cp_endofpacket;                               // bridge_0_avalon_master_agent:cp_endofpacket -> router:sink_endofpacket
	wire         router_src_valid;                                                          // router:src_valid -> cmd_demux:sink_valid
	wire  [74:0] router_src_data;                                                           // router:src_data -> cmd_demux:sink_data
	wire         router_src_ready;                                                          // cmd_demux:sink_ready -> router:src_ready
	wire   [1:0] router_src_channel;                                                        // router:src_channel -> cmd_demux:sink_channel
	wire         router_src_startofpacket;                                                  // router:src_startofpacket -> cmd_demux:sink_startofpacket
	wire         router_src_endofpacket;                                                    // router:src_endofpacket -> cmd_demux:sink_endofpacket
	wire         sdram_pll_pll_slave_agent_rp_valid;                                        // sdram_pll_pll_slave_agent:rp_valid -> router_001:sink_valid
	wire  [92:0] sdram_pll_pll_slave_agent_rp_data;                                         // sdram_pll_pll_slave_agent:rp_data -> router_001:sink_data
	wire         sdram_pll_pll_slave_agent_rp_ready;                                        // router_001:sink_ready -> sdram_pll_pll_slave_agent:rp_ready
	wire         sdram_pll_pll_slave_agent_rp_startofpacket;                                // sdram_pll_pll_slave_agent:rp_startofpacket -> router_001:sink_startofpacket
	wire         sdram_pll_pll_slave_agent_rp_endofpacket;                                  // sdram_pll_pll_slave_agent:rp_endofpacket -> router_001:sink_endofpacket
	wire         bitmap_sdram_s1_agent_rp_valid;                                            // bitmap_sdram_s1_agent:rp_valid -> router_002:sink_valid
	wire  [74:0] bitmap_sdram_s1_agent_rp_data;                                             // bitmap_sdram_s1_agent:rp_data -> router_002:sink_data
	wire         bitmap_sdram_s1_agent_rp_ready;                                            // router_002:sink_ready -> bitmap_sdram_s1_agent:rp_ready
	wire         bitmap_sdram_s1_agent_rp_startofpacket;                                    // bitmap_sdram_s1_agent:rp_startofpacket -> router_002:sink_startofpacket
	wire         bitmap_sdram_s1_agent_rp_endofpacket;                                      // bitmap_sdram_s1_agent:rp_endofpacket -> router_002:sink_endofpacket
	wire         router_002_src_valid;                                                      // router_002:src_valid -> rsp_demux_001:sink_valid
	wire  [74:0] router_002_src_data;                                                       // router_002:src_data -> rsp_demux_001:sink_data
	wire         router_002_src_ready;                                                      // rsp_demux_001:sink_ready -> router_002:src_ready
	wire   [1:0] router_002_src_channel;                                                    // router_002:src_channel -> rsp_demux_001:sink_channel
	wire         router_002_src_startofpacket;                                              // router_002:src_startofpacket -> rsp_demux_001:sink_startofpacket
	wire         router_002_src_endofpacket;                                                // router_002:src_endofpacket -> rsp_demux_001:sink_endofpacket
	wire         cmd_demux_src0_valid;                                                      // cmd_demux:src0_valid -> cmd_mux:sink0_valid
	wire  [74:0] cmd_demux_src0_data;                                                       // cmd_demux:src0_data -> cmd_mux:sink0_data
	wire         cmd_demux_src0_ready;                                                      // cmd_mux:sink0_ready -> cmd_demux:src0_ready
	wire   [1:0] cmd_demux_src0_channel;                                                    // cmd_demux:src0_channel -> cmd_mux:sink0_channel
	wire         cmd_demux_src0_startofpacket;                                              // cmd_demux:src0_startofpacket -> cmd_mux:sink0_startofpacket
	wire         cmd_demux_src0_endofpacket;                                                // cmd_demux:src0_endofpacket -> cmd_mux:sink0_endofpacket
	wire         rsp_demux_src0_valid;                                                      // rsp_demux:src0_valid -> rsp_mux:sink0_valid
	wire  [74:0] rsp_demux_src0_data;                                                       // rsp_demux:src0_data -> rsp_mux:sink0_data
	wire         rsp_demux_src0_ready;                                                      // rsp_mux:sink0_ready -> rsp_demux:src0_ready
	wire   [1:0] rsp_demux_src0_channel;                                                    // rsp_demux:src0_channel -> rsp_mux:sink0_channel
	wire         rsp_demux_src0_startofpacket;                                              // rsp_demux:src0_startofpacket -> rsp_mux:sink0_startofpacket
	wire         rsp_demux_src0_endofpacket;                                                // rsp_demux:src0_endofpacket -> rsp_mux:sink0_endofpacket
	wire         cmd_mux_src_valid;                                                         // cmd_mux:src_valid -> sdram_pll_pll_slave_cmd_width_adapter:in_valid
	wire  [74:0] cmd_mux_src_data;                                                          // cmd_mux:src_data -> sdram_pll_pll_slave_cmd_width_adapter:in_data
	wire         cmd_mux_src_ready;                                                         // sdram_pll_pll_slave_cmd_width_adapter:in_ready -> cmd_mux:src_ready
	wire   [1:0] cmd_mux_src_channel;                                                       // cmd_mux:src_channel -> sdram_pll_pll_slave_cmd_width_adapter:in_channel
	wire         cmd_mux_src_startofpacket;                                                 // cmd_mux:src_startofpacket -> sdram_pll_pll_slave_cmd_width_adapter:in_startofpacket
	wire         cmd_mux_src_endofpacket;                                                   // cmd_mux:src_endofpacket -> sdram_pll_pll_slave_cmd_width_adapter:in_endofpacket
	wire         sdram_pll_pll_slave_cmd_width_adapter_src_valid;                           // sdram_pll_pll_slave_cmd_width_adapter:out_valid -> sdram_pll_pll_slave_agent:cp_valid
	wire  [92:0] sdram_pll_pll_slave_cmd_width_adapter_src_data;                            // sdram_pll_pll_slave_cmd_width_adapter:out_data -> sdram_pll_pll_slave_agent:cp_data
	wire         sdram_pll_pll_slave_cmd_width_adapter_src_ready;                           // sdram_pll_pll_slave_agent:cp_ready -> sdram_pll_pll_slave_cmd_width_adapter:out_ready
	wire   [1:0] sdram_pll_pll_slave_cmd_width_adapter_src_channel;                         // sdram_pll_pll_slave_cmd_width_adapter:out_channel -> sdram_pll_pll_slave_agent:cp_channel
	wire         sdram_pll_pll_slave_cmd_width_adapter_src_startofpacket;                   // sdram_pll_pll_slave_cmd_width_adapter:out_startofpacket -> sdram_pll_pll_slave_agent:cp_startofpacket
	wire         sdram_pll_pll_slave_cmd_width_adapter_src_endofpacket;                     // sdram_pll_pll_slave_cmd_width_adapter:out_endofpacket -> sdram_pll_pll_slave_agent:cp_endofpacket
	wire         router_001_src_valid;                                                      // router_001:src_valid -> sdram_pll_pll_slave_rsp_width_adapter:in_valid
	wire  [92:0] router_001_src_data;                                                       // router_001:src_data -> sdram_pll_pll_slave_rsp_width_adapter:in_data
	wire         router_001_src_ready;                                                      // sdram_pll_pll_slave_rsp_width_adapter:in_ready -> router_001:src_ready
	wire   [1:0] router_001_src_channel;                                                    // router_001:src_channel -> sdram_pll_pll_slave_rsp_width_adapter:in_channel
	wire         router_001_src_startofpacket;                                              // router_001:src_startofpacket -> sdram_pll_pll_slave_rsp_width_adapter:in_startofpacket
	wire         router_001_src_endofpacket;                                                // router_001:src_endofpacket -> sdram_pll_pll_slave_rsp_width_adapter:in_endofpacket
	wire         sdram_pll_pll_slave_rsp_width_adapter_src_valid;                           // sdram_pll_pll_slave_rsp_width_adapter:out_valid -> rsp_demux:sink_valid
	wire  [74:0] sdram_pll_pll_slave_rsp_width_adapter_src_data;                            // sdram_pll_pll_slave_rsp_width_adapter:out_data -> rsp_demux:sink_data
	wire         sdram_pll_pll_slave_rsp_width_adapter_src_ready;                           // rsp_demux:sink_ready -> sdram_pll_pll_slave_rsp_width_adapter:out_ready
	wire   [1:0] sdram_pll_pll_slave_rsp_width_adapter_src_channel;                         // sdram_pll_pll_slave_rsp_width_adapter:out_channel -> rsp_demux:sink_channel
	wire         sdram_pll_pll_slave_rsp_width_adapter_src_startofpacket;                   // sdram_pll_pll_slave_rsp_width_adapter:out_startofpacket -> rsp_demux:sink_startofpacket
	wire         sdram_pll_pll_slave_rsp_width_adapter_src_endofpacket;                     // sdram_pll_pll_slave_rsp_width_adapter:out_endofpacket -> rsp_demux:sink_endofpacket
	wire         cmd_demux_src1_valid;                                                      // cmd_demux:src1_valid -> crosser:in_valid
	wire  [74:0] cmd_demux_src1_data;                                                       // cmd_demux:src1_data -> crosser:in_data
	wire         cmd_demux_src1_ready;                                                      // crosser:in_ready -> cmd_demux:src1_ready
	wire   [1:0] cmd_demux_src1_channel;                                                    // cmd_demux:src1_channel -> crosser:in_channel
	wire         cmd_demux_src1_startofpacket;                                              // cmd_demux:src1_startofpacket -> crosser:in_startofpacket
	wire         cmd_demux_src1_endofpacket;                                                // cmd_demux:src1_endofpacket -> crosser:in_endofpacket
	wire         crosser_out_valid;                                                         // crosser:out_valid -> cmd_mux_001:sink0_valid
	wire  [74:0] crosser_out_data;                                                          // crosser:out_data -> cmd_mux_001:sink0_data
	wire         crosser_out_ready;                                                         // cmd_mux_001:sink0_ready -> crosser:out_ready
	wire   [1:0] crosser_out_channel;                                                       // crosser:out_channel -> cmd_mux_001:sink0_channel
	wire         crosser_out_startofpacket;                                                 // crosser:out_startofpacket -> cmd_mux_001:sink0_startofpacket
	wire         crosser_out_endofpacket;                                                   // crosser:out_endofpacket -> cmd_mux_001:sink0_endofpacket
	wire         rsp_demux_001_src0_valid;                                                  // rsp_demux_001:src0_valid -> crosser_001:in_valid
	wire  [74:0] rsp_demux_001_src0_data;                                                   // rsp_demux_001:src0_data -> crosser_001:in_data
	wire         rsp_demux_001_src0_ready;                                                  // crosser_001:in_ready -> rsp_demux_001:src0_ready
	wire   [1:0] rsp_demux_001_src0_channel;                                                // rsp_demux_001:src0_channel -> crosser_001:in_channel
	wire         rsp_demux_001_src0_startofpacket;                                          // rsp_demux_001:src0_startofpacket -> crosser_001:in_startofpacket
	wire         rsp_demux_001_src0_endofpacket;                                            // rsp_demux_001:src0_endofpacket -> crosser_001:in_endofpacket
	wire         crosser_001_out_valid;                                                     // crosser_001:out_valid -> rsp_mux:sink1_valid
	wire  [74:0] crosser_001_out_data;                                                      // crosser_001:out_data -> rsp_mux:sink1_data
	wire         crosser_001_out_ready;                                                     // rsp_mux:sink1_ready -> crosser_001:out_ready
	wire   [1:0] crosser_001_out_channel;                                                   // crosser_001:out_channel -> rsp_mux:sink1_channel
	wire         crosser_001_out_startofpacket;                                             // crosser_001:out_startofpacket -> rsp_mux:sink1_startofpacket
	wire         crosser_001_out_endofpacket;                                               // crosser_001:out_endofpacket -> rsp_mux:sink1_endofpacket
	wire         sdram_pll_pll_slave_agent_rdata_fifo_src_valid;                            // sdram_pll_pll_slave_agent:rdata_fifo_src_valid -> avalon_st_adapter:in_0_valid
	wire  [33:0] sdram_pll_pll_slave_agent_rdata_fifo_src_data;                             // sdram_pll_pll_slave_agent:rdata_fifo_src_data -> avalon_st_adapter:in_0_data
	wire         sdram_pll_pll_slave_agent_rdata_fifo_src_ready;                            // avalon_st_adapter:in_0_ready -> sdram_pll_pll_slave_agent:rdata_fifo_src_ready
	wire         avalon_st_adapter_out_0_valid;                                             // avalon_st_adapter:out_0_valid -> sdram_pll_pll_slave_agent:rdata_fifo_sink_valid
	wire  [33:0] avalon_st_adapter_out_0_data;                                              // avalon_st_adapter:out_0_data -> sdram_pll_pll_slave_agent:rdata_fifo_sink_data
	wire         avalon_st_adapter_out_0_ready;                                             // sdram_pll_pll_slave_agent:rdata_fifo_sink_ready -> avalon_st_adapter:out_0_ready
	wire   [0:0] avalon_st_adapter_out_0_error;                                             // avalon_st_adapter:out_0_error -> sdram_pll_pll_slave_agent:rdata_fifo_sink_error
	wire         bitmap_sdram_s1_agent_rdata_fifo_out_valid;                                // bitmap_sdram_s1_agent_rdata_fifo:out_valid -> avalon_st_adapter_001:in_0_valid
	wire  [17:0] bitmap_sdram_s1_agent_rdata_fifo_out_data;                                 // bitmap_sdram_s1_agent_rdata_fifo:out_data -> avalon_st_adapter_001:in_0_data
	wire         bitmap_sdram_s1_agent_rdata_fifo_out_ready;                                // avalon_st_adapter_001:in_0_ready -> bitmap_sdram_s1_agent_rdata_fifo:out_ready
	wire         avalon_st_adapter_001_out_0_valid;                                         // avalon_st_adapter_001:out_0_valid -> bitmap_sdram_s1_agent:rdata_fifo_sink_valid
	wire  [17:0] avalon_st_adapter_001_out_0_data;                                          // avalon_st_adapter_001:out_0_data -> bitmap_sdram_s1_agent:rdata_fifo_sink_data
	wire         avalon_st_adapter_001_out_0_ready;                                         // bitmap_sdram_s1_agent:rdata_fifo_sink_ready -> avalon_st_adapter_001:out_0_ready
	wire   [0:0] avalon_st_adapter_001_out_0_error;                                         // avalon_st_adapter_001:out_0_error -> bitmap_sdram_s1_agent:rdata_fifo_sink_error

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (23),
		.AV_DATA_W                   (16),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (2),
		.UAV_ADDRESS_W               (23),
		.UAV_BURSTCOUNT_W            (2),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (0),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (2),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) bridge_0_avalon_master_translator (
		.clk                    (clk_0_clk_clk),                                                             //                       clk.clk
		.reset                  (bridge_0_reset_reset_bridge_in_reset_reset),                                //                     reset.reset
		.uav_address            (bridge_0_avalon_master_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (bridge_0_avalon_master_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (bridge_0_avalon_master_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (bridge_0_avalon_master_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (bridge_0_avalon_master_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (bridge_0_avalon_master_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (bridge_0_avalon_master_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (bridge_0_avalon_master_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (bridge_0_avalon_master_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (bridge_0_avalon_master_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (bridge_0_avalon_master_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (bridge_0_avalon_master_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (bridge_0_avalon_master_waitrequest),                                        //                          .waitrequest
		.av_byteenable          (bridge_0_avalon_master_byteenable),                                         //                          .byteenable
		.av_read                (bridge_0_avalon_master_read),                                               //                          .read
		.av_readdata            (bridge_0_avalon_master_readdata),                                           //                          .readdata
		.av_write               (bridge_0_avalon_master_write),                                              //                          .write
		.av_writedata           (bridge_0_avalon_master_writedata),                                          //                          .writedata
		.av_burstcount          (1'b1),                                                                      //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                                      //               (terminated)
		.av_begintransfer       (1'b0),                                                                      //               (terminated)
		.av_chipselect          (1'b0),                                                                      //               (terminated)
		.av_readdatavalid       (),                                                                          //               (terminated)
		.av_lock                (1'b0),                                                                      //               (terminated)
		.av_debugaccess         (1'b0),                                                                      //               (terminated)
		.uav_clken              (),                                                                          //               (terminated)
		.av_clken               (1'b1),                                                                      //               (terminated)
		.uav_response           (2'b00),                                                                     //               (terminated)
		.av_response            (),                                                                          //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                      //               (terminated)
		.av_writeresponsevalid  ()                                                                           //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (2),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (23),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (0),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) sdram_pll_pll_slave_translator (
		.clk                    (clk_0_clk_clk),                              //                      clk.clk
		.reset                  (bridge_0_reset_reset_bridge_in_reset_reset), //                    reset.reset
		.uav_address            (sdram_pll_pll_slave_agent_m0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (sdram_pll_pll_slave_agent_m0_burstcount),    //                         .burstcount
		.uav_read               (sdram_pll_pll_slave_agent_m0_read),          //                         .read
		.uav_write              (sdram_pll_pll_slave_agent_m0_write),         //                         .write
		.uav_waitrequest        (sdram_pll_pll_slave_agent_m0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (sdram_pll_pll_slave_agent_m0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (sdram_pll_pll_slave_agent_m0_byteenable),    //                         .byteenable
		.uav_readdata           (sdram_pll_pll_slave_agent_m0_readdata),      //                         .readdata
		.uav_writedata          (sdram_pll_pll_slave_agent_m0_writedata),     //                         .writedata
		.uav_lock               (sdram_pll_pll_slave_agent_m0_lock),          //                         .lock
		.uav_debugaccess        (sdram_pll_pll_slave_agent_m0_debugaccess),   //                         .debugaccess
		.av_address             (sdram_pll_pll_slave_address),                //      avalon_anti_slave_0.address
		.av_write               (sdram_pll_pll_slave_write),                  //                         .write
		.av_read                (sdram_pll_pll_slave_read),                   //                         .read
		.av_readdata            (sdram_pll_pll_slave_readdata),               //                         .readdata
		.av_writedata           (sdram_pll_pll_slave_writedata),              //                         .writedata
		.av_begintransfer       (),                                           //              (terminated)
		.av_beginbursttransfer  (),                                           //              (terminated)
		.av_burstcount          (),                                           //              (terminated)
		.av_byteenable          (),                                           //              (terminated)
		.av_readdatavalid       (1'b0),                                       //              (terminated)
		.av_waitrequest         (1'b0),                                       //              (terminated)
		.av_writebyteenable     (),                                           //              (terminated)
		.av_lock                (),                                           //              (terminated)
		.av_chipselect          (),                                           //              (terminated)
		.av_clken               (),                                           //              (terminated)
		.uav_clken              (1'b0),                                       //              (terminated)
		.av_debugaccess         (),                                           //              (terminated)
		.av_outputenable        (),                                           //              (terminated)
		.uav_response           (),                                           //              (terminated)
		.av_response            (2'b00),                                      //              (terminated)
		.uav_writeresponsevalid (),                                           //              (terminated)
		.av_writeresponsevalid  (1'b0)                                        //              (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (21),
		.AV_DATA_W                      (16),
		.UAV_DATA_W                     (16),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (2),
		.UAV_BYTEENABLE_W               (2),
		.UAV_ADDRESS_W                  (23),
		.UAV_BURSTCOUNT_W               (2),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (1),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (2),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (1),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) bitmap_sdram_s1_translator (
		.clk                    (sdram_pll_c0_clk),                               //                      clk.clk
		.reset                  (bitmap_sdram_reset_reset_bridge_in_reset_reset), //                    reset.reset
		.uav_address            (bitmap_sdram_s1_agent_m0_address),               // avalon_universal_slave_0.address
		.uav_burstcount         (bitmap_sdram_s1_agent_m0_burstcount),            //                         .burstcount
		.uav_read               (bitmap_sdram_s1_agent_m0_read),                  //                         .read
		.uav_write              (bitmap_sdram_s1_agent_m0_write),                 //                         .write
		.uav_waitrequest        (bitmap_sdram_s1_agent_m0_waitrequest),           //                         .waitrequest
		.uav_readdatavalid      (bitmap_sdram_s1_agent_m0_readdatavalid),         //                         .readdatavalid
		.uav_byteenable         (bitmap_sdram_s1_agent_m0_byteenable),            //                         .byteenable
		.uav_readdata           (bitmap_sdram_s1_agent_m0_readdata),              //                         .readdata
		.uav_writedata          (bitmap_sdram_s1_agent_m0_writedata),             //                         .writedata
		.uav_lock               (bitmap_sdram_s1_agent_m0_lock),                  //                         .lock
		.uav_debugaccess        (bitmap_sdram_s1_agent_m0_debugaccess),           //                         .debugaccess
		.av_address             (bitmap_sdram_s1_address),                        //      avalon_anti_slave_0.address
		.av_write               (bitmap_sdram_s1_write),                          //                         .write
		.av_read                (bitmap_sdram_s1_read),                           //                         .read
		.av_readdata            (bitmap_sdram_s1_readdata),                       //                         .readdata
		.av_writedata           (bitmap_sdram_s1_writedata),                      //                         .writedata
		.av_byteenable          (bitmap_sdram_s1_byteenable),                     //                         .byteenable
		.av_readdatavalid       (bitmap_sdram_s1_readdatavalid),                  //                         .readdatavalid
		.av_waitrequest         (bitmap_sdram_s1_waitrequest),                    //                         .waitrequest
		.av_chipselect          (bitmap_sdram_s1_chipselect),                     //                         .chipselect
		.av_begintransfer       (),                                               //              (terminated)
		.av_beginbursttransfer  (),                                               //              (terminated)
		.av_burstcount          (),                                               //              (terminated)
		.av_writebyteenable     (),                                               //              (terminated)
		.av_lock                (),                                               //              (terminated)
		.av_clken               (),                                               //              (terminated)
		.uav_clken              (1'b0),                                           //              (terminated)
		.av_debugaccess         (),                                               //              (terminated)
		.av_outputenable        (),                                               //              (terminated)
		.uav_response           (),                                               //              (terminated)
		.av_response            (2'b00),                                          //              (terminated)
		.uav_writeresponsevalid (),                                               //              (terminated)
		.av_writeresponsevalid  (1'b0)                                            //              (terminated)
	);

	altera_merlin_master_agent #(
		.PKT_ORI_BURST_SIZE_H      (74),
		.PKT_ORI_BURST_SIZE_L      (72),
		.PKT_RESPONSE_STATUS_H     (71),
		.PKT_RESPONSE_STATUS_L     (70),
		.PKT_QOS_H                 (59),
		.PKT_QOS_L                 (59),
		.PKT_DATA_SIDEBAND_H       (57),
		.PKT_DATA_SIDEBAND_L       (57),
		.PKT_ADDR_SIDEBAND_H       (56),
		.PKT_ADDR_SIDEBAND_L       (56),
		.PKT_BURST_TYPE_H          (55),
		.PKT_BURST_TYPE_L          (54),
		.PKT_CACHE_H               (69),
		.PKT_CACHE_L               (66),
		.PKT_THREAD_ID_H           (62),
		.PKT_THREAD_ID_L           (62),
		.PKT_BURST_SIZE_H          (53),
		.PKT_BURST_SIZE_L          (51),
		.PKT_TRANS_EXCLUSIVE       (46),
		.PKT_TRANS_LOCK            (45),
		.PKT_BEGIN_BURST           (58),
		.PKT_PROTECTION_H          (65),
		.PKT_PROTECTION_L          (63),
		.PKT_BURSTWRAP_H           (50),
		.PKT_BURSTWRAP_L           (50),
		.PKT_BYTE_CNT_H            (49),
		.PKT_BYTE_CNT_L            (47),
		.PKT_ADDR_H                (40),
		.PKT_ADDR_L                (18),
		.PKT_TRANS_COMPRESSED_READ (41),
		.PKT_TRANS_POSTED          (42),
		.PKT_TRANS_WRITE           (43),
		.PKT_TRANS_READ            (44),
		.PKT_DATA_H                (15),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (17),
		.PKT_BYTEEN_L              (16),
		.PKT_SRC_ID_H              (60),
		.PKT_SRC_ID_L              (60),
		.PKT_DEST_ID_H             (61),
		.PKT_DEST_ID_L             (61),
		.ST_DATA_W                 (75),
		.ST_CHANNEL_W              (2),
		.AV_BURSTCOUNT_W           (2),
		.SUPPRESS_0_BYTEEN_RSP     (1),
		.ID                        (0),
		.BURSTWRAP_VALUE           (1),
		.CACHE_VALUE               (0),
		.SECURE_ACCESS_BIT         (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0)
	) bridge_0_avalon_master_agent (
		.clk                   (clk_0_clk_clk),                                                             //       clk.clk
		.reset                 (bridge_0_reset_reset_bridge_in_reset_reset),                                // clk_reset.reset
		.av_address            (bridge_0_avalon_master_translator_avalon_universal_master_0_address),       //        av.address
		.av_write              (bridge_0_avalon_master_translator_avalon_universal_master_0_write),         //          .write
		.av_read               (bridge_0_avalon_master_translator_avalon_universal_master_0_read),          //          .read
		.av_writedata          (bridge_0_avalon_master_translator_avalon_universal_master_0_writedata),     //          .writedata
		.av_readdata           (bridge_0_avalon_master_translator_avalon_universal_master_0_readdata),      //          .readdata
		.av_waitrequest        (bridge_0_avalon_master_translator_avalon_universal_master_0_waitrequest),   //          .waitrequest
		.av_readdatavalid      (bridge_0_avalon_master_translator_avalon_universal_master_0_readdatavalid), //          .readdatavalid
		.av_byteenable         (bridge_0_avalon_master_translator_avalon_universal_master_0_byteenable),    //          .byteenable
		.av_burstcount         (bridge_0_avalon_master_translator_avalon_universal_master_0_burstcount),    //          .burstcount
		.av_debugaccess        (bridge_0_avalon_master_translator_avalon_universal_master_0_debugaccess),   //          .debugaccess
		.av_lock               (bridge_0_avalon_master_translator_avalon_universal_master_0_lock),          //          .lock
		.cp_valid              (bridge_0_avalon_master_agent_cp_valid),                                     //        cp.valid
		.cp_data               (bridge_0_avalon_master_agent_cp_data),                                      //          .data
		.cp_startofpacket      (bridge_0_avalon_master_agent_cp_startofpacket),                             //          .startofpacket
		.cp_endofpacket        (bridge_0_avalon_master_agent_cp_endofpacket),                               //          .endofpacket
		.cp_ready              (bridge_0_avalon_master_agent_cp_ready),                                     //          .ready
		.rp_valid              (rsp_mux_src_valid),                                                         //        rp.valid
		.rp_data               (rsp_mux_src_data),                                                          //          .data
		.rp_channel            (rsp_mux_src_channel),                                                       //          .channel
		.rp_startofpacket      (rsp_mux_src_startofpacket),                                                 //          .startofpacket
		.rp_endofpacket        (rsp_mux_src_endofpacket),                                                   //          .endofpacket
		.rp_ready              (rsp_mux_src_ready),                                                         //          .ready
		.av_response           (),                                                                          // (terminated)
		.av_writeresponsevalid ()                                                                           // (terminated)
	);

	altera_merlin_slave_agent #(
		.PKT_ORI_BURST_SIZE_H      (92),
		.PKT_ORI_BURST_SIZE_L      (90),
		.PKT_RESPONSE_STATUS_H     (89),
		.PKT_RESPONSE_STATUS_L     (88),
		.PKT_BURST_SIZE_H          (71),
		.PKT_BURST_SIZE_L          (69),
		.PKT_TRANS_LOCK            (63),
		.PKT_BEGIN_BURST           (76),
		.PKT_PROTECTION_H          (83),
		.PKT_PROTECTION_L          (81),
		.PKT_BURSTWRAP_H           (68),
		.PKT_BURSTWRAP_L           (68),
		.PKT_BYTE_CNT_H            (67),
		.PKT_BYTE_CNT_L            (65),
		.PKT_ADDR_H                (58),
		.PKT_ADDR_L                (36),
		.PKT_TRANS_COMPRESSED_READ (59),
		.PKT_TRANS_POSTED          (60),
		.PKT_TRANS_WRITE           (61),
		.PKT_TRANS_READ            (62),
		.PKT_DATA_H                (31),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_SRC_ID_H              (78),
		.PKT_SRC_ID_L              (78),
		.PKT_DEST_ID_H             (79),
		.PKT_DEST_ID_L             (79),
		.PKT_SYMBOL_W              (8),
		.ST_CHANNEL_W              (2),
		.ST_DATA_W                 (93),
		.AVS_BURSTCOUNT_W          (3),
		.SUPPRESS_0_BYTEEN_CMD     (0),
		.PREVENT_FIFO_OVERFLOW     (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0),
		.ECC_ENABLE                (0)
	) sdram_pll_pll_slave_agent (
		.clk                     (clk_0_clk_clk),                                           //             clk.clk
		.reset                   (bridge_0_reset_reset_bridge_in_reset_reset),              //       clk_reset.reset
		.m0_address              (sdram_pll_pll_slave_agent_m0_address),                    //              m0.address
		.m0_burstcount           (sdram_pll_pll_slave_agent_m0_burstcount),                 //                .burstcount
		.m0_byteenable           (sdram_pll_pll_slave_agent_m0_byteenable),                 //                .byteenable
		.m0_debugaccess          (sdram_pll_pll_slave_agent_m0_debugaccess),                //                .debugaccess
		.m0_lock                 (sdram_pll_pll_slave_agent_m0_lock),                       //                .lock
		.m0_readdata             (sdram_pll_pll_slave_agent_m0_readdata),                   //                .readdata
		.m0_readdatavalid        (sdram_pll_pll_slave_agent_m0_readdatavalid),              //                .readdatavalid
		.m0_read                 (sdram_pll_pll_slave_agent_m0_read),                       //                .read
		.m0_waitrequest          (sdram_pll_pll_slave_agent_m0_waitrequest),                //                .waitrequest
		.m0_writedata            (sdram_pll_pll_slave_agent_m0_writedata),                  //                .writedata
		.m0_write                (sdram_pll_pll_slave_agent_m0_write),                      //                .write
		.rp_endofpacket          (sdram_pll_pll_slave_agent_rp_endofpacket),                //              rp.endofpacket
		.rp_ready                (sdram_pll_pll_slave_agent_rp_ready),                      //                .ready
		.rp_valid                (sdram_pll_pll_slave_agent_rp_valid),                      //                .valid
		.rp_data                 (sdram_pll_pll_slave_agent_rp_data),                       //                .data
		.rp_startofpacket        (sdram_pll_pll_slave_agent_rp_startofpacket),              //                .startofpacket
		.cp_ready                (sdram_pll_pll_slave_cmd_width_adapter_src_ready),         //              cp.ready
		.cp_valid                (sdram_pll_pll_slave_cmd_width_adapter_src_valid),         //                .valid
		.cp_data                 (sdram_pll_pll_slave_cmd_width_adapter_src_data),          //                .data
		.cp_startofpacket        (sdram_pll_pll_slave_cmd_width_adapter_src_startofpacket), //                .startofpacket
		.cp_endofpacket          (sdram_pll_pll_slave_cmd_width_adapter_src_endofpacket),   //                .endofpacket
		.cp_channel              (sdram_pll_pll_slave_cmd_width_adapter_src_channel),       //                .channel
		.rf_sink_ready           (sdram_pll_pll_slave_agent_rsp_fifo_out_ready),            //         rf_sink.ready
		.rf_sink_valid           (sdram_pll_pll_slave_agent_rsp_fifo_out_valid),            //                .valid
		.rf_sink_startofpacket   (sdram_pll_pll_slave_agent_rsp_fifo_out_startofpacket),    //                .startofpacket
		.rf_sink_endofpacket     (sdram_pll_pll_slave_agent_rsp_fifo_out_endofpacket),      //                .endofpacket
		.rf_sink_data            (sdram_pll_pll_slave_agent_rsp_fifo_out_data),             //                .data
		.rf_source_ready         (sdram_pll_pll_slave_agent_rf_source_ready),               //       rf_source.ready
		.rf_source_valid         (sdram_pll_pll_slave_agent_rf_source_valid),               //                .valid
		.rf_source_startofpacket (sdram_pll_pll_slave_agent_rf_source_startofpacket),       //                .startofpacket
		.rf_source_endofpacket   (sdram_pll_pll_slave_agent_rf_source_endofpacket),         //                .endofpacket
		.rf_source_data          (sdram_pll_pll_slave_agent_rf_source_data),                //                .data
		.rdata_fifo_sink_ready   (avalon_st_adapter_out_0_ready),                           // rdata_fifo_sink.ready
		.rdata_fifo_sink_valid   (avalon_st_adapter_out_0_valid),                           //                .valid
		.rdata_fifo_sink_data    (avalon_st_adapter_out_0_data),                            //                .data
		.rdata_fifo_sink_error   (avalon_st_adapter_out_0_error),                           //                .error
		.rdata_fifo_src_ready    (sdram_pll_pll_slave_agent_rdata_fifo_src_ready),          //  rdata_fifo_src.ready
		.rdata_fifo_src_valid    (sdram_pll_pll_slave_agent_rdata_fifo_src_valid),          //                .valid
		.rdata_fifo_src_data     (sdram_pll_pll_slave_agent_rdata_fifo_src_data),           //                .data
		.m0_response             (2'b00),                                                   //     (terminated)
		.m0_writeresponsevalid   (1'b0)                                                     //     (terminated)
	);

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (94),
		.FIFO_DEPTH          (2),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (1),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (1),
		.USE_MEMORY_BLOCKS   (0),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0)
	) sdram_pll_pll_slave_agent_rsp_fifo (
		.clk               (clk_0_clk_clk),                                        //       clk.clk
		.reset             (bridge_0_reset_reset_bridge_in_reset_reset),           // clk_reset.reset
		.in_data           (sdram_pll_pll_slave_agent_rf_source_data),             //        in.data
		.in_valid          (sdram_pll_pll_slave_agent_rf_source_valid),            //          .valid
		.in_ready          (sdram_pll_pll_slave_agent_rf_source_ready),            //          .ready
		.in_startofpacket  (sdram_pll_pll_slave_agent_rf_source_startofpacket),    //          .startofpacket
		.in_endofpacket    (sdram_pll_pll_slave_agent_rf_source_endofpacket),      //          .endofpacket
		.out_data          (sdram_pll_pll_slave_agent_rsp_fifo_out_data),          //       out.data
		.out_valid         (sdram_pll_pll_slave_agent_rsp_fifo_out_valid),         //          .valid
		.out_ready         (sdram_pll_pll_slave_agent_rsp_fifo_out_ready),         //          .ready
		.out_startofpacket (sdram_pll_pll_slave_agent_rsp_fifo_out_startofpacket), //          .startofpacket
		.out_endofpacket   (sdram_pll_pll_slave_agent_rsp_fifo_out_endofpacket),   //          .endofpacket
		.csr_address       (2'b00),                                                // (terminated)
		.csr_read          (1'b0),                                                 // (terminated)
		.csr_write         (1'b0),                                                 // (terminated)
		.csr_readdata      (),                                                     // (terminated)
		.csr_writedata     (32'b00000000000000000000000000000000),                 // (terminated)
		.almost_full_data  (),                                                     // (terminated)
		.almost_empty_data (),                                                     // (terminated)
		.in_empty          (1'b0),                                                 // (terminated)
		.out_empty         (),                                                     // (terminated)
		.in_error          (1'b0),                                                 // (terminated)
		.out_error         (),                                                     // (terminated)
		.in_channel        (1'b0),                                                 // (terminated)
		.out_channel       ()                                                      // (terminated)
	);

	altera_merlin_slave_agent #(
		.PKT_ORI_BURST_SIZE_H      (74),
		.PKT_ORI_BURST_SIZE_L      (72),
		.PKT_RESPONSE_STATUS_H     (71),
		.PKT_RESPONSE_STATUS_L     (70),
		.PKT_BURST_SIZE_H          (53),
		.PKT_BURST_SIZE_L          (51),
		.PKT_TRANS_LOCK            (45),
		.PKT_BEGIN_BURST           (58),
		.PKT_PROTECTION_H          (65),
		.PKT_PROTECTION_L          (63),
		.PKT_BURSTWRAP_H           (50),
		.PKT_BURSTWRAP_L           (50),
		.PKT_BYTE_CNT_H            (49),
		.PKT_BYTE_CNT_L            (47),
		.PKT_ADDR_H                (40),
		.PKT_ADDR_L                (18),
		.PKT_TRANS_COMPRESSED_READ (41),
		.PKT_TRANS_POSTED          (42),
		.PKT_TRANS_WRITE           (43),
		.PKT_TRANS_READ            (44),
		.PKT_DATA_H                (15),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (17),
		.PKT_BYTEEN_L              (16),
		.PKT_SRC_ID_H              (60),
		.PKT_SRC_ID_L              (60),
		.PKT_DEST_ID_H             (61),
		.PKT_DEST_ID_L             (61),
		.PKT_SYMBOL_W              (8),
		.ST_CHANNEL_W              (2),
		.ST_DATA_W                 (75),
		.AVS_BURSTCOUNT_W          (2),
		.SUPPRESS_0_BYTEEN_CMD     (0),
		.PREVENT_FIFO_OVERFLOW     (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0),
		.ECC_ENABLE                (0)
	) bitmap_sdram_s1_agent (
		.clk                     (sdram_pll_c0_clk),                                 //             clk.clk
		.reset                   (bitmap_sdram_reset_reset_bridge_in_reset_reset),   //       clk_reset.reset
		.m0_address              (bitmap_sdram_s1_agent_m0_address),                 //              m0.address
		.m0_burstcount           (bitmap_sdram_s1_agent_m0_burstcount),              //                .burstcount
		.m0_byteenable           (bitmap_sdram_s1_agent_m0_byteenable),              //                .byteenable
		.m0_debugaccess          (bitmap_sdram_s1_agent_m0_debugaccess),             //                .debugaccess
		.m0_lock                 (bitmap_sdram_s1_agent_m0_lock),                    //                .lock
		.m0_readdata             (bitmap_sdram_s1_agent_m0_readdata),                //                .readdata
		.m0_readdatavalid        (bitmap_sdram_s1_agent_m0_readdatavalid),           //                .readdatavalid
		.m0_read                 (bitmap_sdram_s1_agent_m0_read),                    //                .read
		.m0_waitrequest          (bitmap_sdram_s1_agent_m0_waitrequest),             //                .waitrequest
		.m0_writedata            (bitmap_sdram_s1_agent_m0_writedata),               //                .writedata
		.m0_write                (bitmap_sdram_s1_agent_m0_write),                   //                .write
		.rp_endofpacket          (bitmap_sdram_s1_agent_rp_endofpacket),             //              rp.endofpacket
		.rp_ready                (bitmap_sdram_s1_agent_rp_ready),                   //                .ready
		.rp_valid                (bitmap_sdram_s1_agent_rp_valid),                   //                .valid
		.rp_data                 (bitmap_sdram_s1_agent_rp_data),                    //                .data
		.rp_startofpacket        (bitmap_sdram_s1_agent_rp_startofpacket),           //                .startofpacket
		.cp_ready                (cmd_mux_001_src_ready),                            //              cp.ready
		.cp_valid                (cmd_mux_001_src_valid),                            //                .valid
		.cp_data                 (cmd_mux_001_src_data),                             //                .data
		.cp_startofpacket        (cmd_mux_001_src_startofpacket),                    //                .startofpacket
		.cp_endofpacket          (cmd_mux_001_src_endofpacket),                      //                .endofpacket
		.cp_channel              (cmd_mux_001_src_channel),                          //                .channel
		.rf_sink_ready           (bitmap_sdram_s1_agent_rsp_fifo_out_ready),         //         rf_sink.ready
		.rf_sink_valid           (bitmap_sdram_s1_agent_rsp_fifo_out_valid),         //                .valid
		.rf_sink_startofpacket   (bitmap_sdram_s1_agent_rsp_fifo_out_startofpacket), //                .startofpacket
		.rf_sink_endofpacket     (bitmap_sdram_s1_agent_rsp_fifo_out_endofpacket),   //                .endofpacket
		.rf_sink_data            (bitmap_sdram_s1_agent_rsp_fifo_out_data),          //                .data
		.rf_source_ready         (bitmap_sdram_s1_agent_rf_source_ready),            //       rf_source.ready
		.rf_source_valid         (bitmap_sdram_s1_agent_rf_source_valid),            //                .valid
		.rf_source_startofpacket (bitmap_sdram_s1_agent_rf_source_startofpacket),    //                .startofpacket
		.rf_source_endofpacket   (bitmap_sdram_s1_agent_rf_source_endofpacket),      //                .endofpacket
		.rf_source_data          (bitmap_sdram_s1_agent_rf_source_data),             //                .data
		.rdata_fifo_sink_ready   (avalon_st_adapter_001_out_0_ready),                // rdata_fifo_sink.ready
		.rdata_fifo_sink_valid   (avalon_st_adapter_001_out_0_valid),                //                .valid
		.rdata_fifo_sink_data    (avalon_st_adapter_001_out_0_data),                 //                .data
		.rdata_fifo_sink_error   (avalon_st_adapter_001_out_0_error),                //                .error
		.rdata_fifo_src_ready    (bitmap_sdram_s1_agent_rdata_fifo_src_ready),       //  rdata_fifo_src.ready
		.rdata_fifo_src_valid    (bitmap_sdram_s1_agent_rdata_fifo_src_valid),       //                .valid
		.rdata_fifo_src_data     (bitmap_sdram_s1_agent_rdata_fifo_src_data),        //                .data
		.m0_response             (2'b00),                                            //     (terminated)
		.m0_writeresponsevalid   (1'b0)                                              //     (terminated)
	);

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (76),
		.FIFO_DEPTH          (8),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (1),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (1),
		.USE_MEMORY_BLOCKS   (0),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0)
	) bitmap_sdram_s1_agent_rsp_fifo (
		.clk               (sdram_pll_c0_clk),                                 //       clk.clk
		.reset             (bitmap_sdram_reset_reset_bridge_in_reset_reset),   // clk_reset.reset
		.in_data           (bitmap_sdram_s1_agent_rf_source_data),             //        in.data
		.in_valid          (bitmap_sdram_s1_agent_rf_source_valid),            //          .valid
		.in_ready          (bitmap_sdram_s1_agent_rf_source_ready),            //          .ready
		.in_startofpacket  (bitmap_sdram_s1_agent_rf_source_startofpacket),    //          .startofpacket
		.in_endofpacket    (bitmap_sdram_s1_agent_rf_source_endofpacket),      //          .endofpacket
		.out_data          (bitmap_sdram_s1_agent_rsp_fifo_out_data),          //       out.data
		.out_valid         (bitmap_sdram_s1_agent_rsp_fifo_out_valid),         //          .valid
		.out_ready         (bitmap_sdram_s1_agent_rsp_fifo_out_ready),         //          .ready
		.out_startofpacket (bitmap_sdram_s1_agent_rsp_fifo_out_startofpacket), //          .startofpacket
		.out_endofpacket   (bitmap_sdram_s1_agent_rsp_fifo_out_endofpacket),   //          .endofpacket
		.csr_address       (2'b00),                                            // (terminated)
		.csr_read          (1'b0),                                             // (terminated)
		.csr_write         (1'b0),                                             // (terminated)
		.csr_readdata      (),                                                 // (terminated)
		.csr_writedata     (32'b00000000000000000000000000000000),             // (terminated)
		.almost_full_data  (),                                                 // (terminated)
		.almost_empty_data (),                                                 // (terminated)
		.in_empty          (1'b0),                                             // (terminated)
		.out_empty         (),                                                 // (terminated)
		.in_error          (1'b0),                                             // (terminated)
		.out_error         (),                                                 // (terminated)
		.in_channel        (1'b0),                                             // (terminated)
		.out_channel       ()                                                  // (terminated)
	);

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (18),
		.FIFO_DEPTH          (8),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (0),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (3),
		.USE_MEMORY_BLOCKS   (1),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0)
	) bitmap_sdram_s1_agent_rdata_fifo (
		.clk               (sdram_pll_c0_clk),                               //       clk.clk
		.reset             (bitmap_sdram_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.in_data           (bitmap_sdram_s1_agent_rdata_fifo_src_data),      //        in.data
		.in_valid          (bitmap_sdram_s1_agent_rdata_fifo_src_valid),     //          .valid
		.in_ready          (bitmap_sdram_s1_agent_rdata_fifo_src_ready),     //          .ready
		.out_data          (bitmap_sdram_s1_agent_rdata_fifo_out_data),      //       out.data
		.out_valid         (bitmap_sdram_s1_agent_rdata_fifo_out_valid),     //          .valid
		.out_ready         (bitmap_sdram_s1_agent_rdata_fifo_out_ready),     //          .ready
		.csr_address       (2'b00),                                          // (terminated)
		.csr_read          (1'b0),                                           // (terminated)
		.csr_write         (1'b0),                                           // (terminated)
		.csr_readdata      (),                                               // (terminated)
		.csr_writedata     (32'b00000000000000000000000000000000),           // (terminated)
		.almost_full_data  (),                                               // (terminated)
		.almost_empty_data (),                                               // (terminated)
		.in_startofpacket  (1'b0),                                           // (terminated)
		.in_endofpacket    (1'b0),                                           // (terminated)
		.out_startofpacket (),                                               // (terminated)
		.out_endofpacket   (),                                               // (terminated)
		.in_empty          (1'b0),                                           // (terminated)
		.out_empty         (),                                               // (terminated)
		.in_error          (1'b0),                                           // (terminated)
		.out_error         (),                                               // (terminated)
		.in_channel        (1'b0),                                           // (terminated)
		.out_channel       ()                                                // (terminated)
	);

	jsv_sdram_mm_interconnect_0_router router (
		.sink_ready         (bridge_0_avalon_master_agent_cp_ready),         //      sink.ready
		.sink_valid         (bridge_0_avalon_master_agent_cp_valid),         //          .valid
		.sink_data          (bridge_0_avalon_master_agent_cp_data),          //          .data
		.sink_startofpacket (bridge_0_avalon_master_agent_cp_startofpacket), //          .startofpacket
		.sink_endofpacket   (bridge_0_avalon_master_agent_cp_endofpacket),   //          .endofpacket
		.clk                (clk_0_clk_clk),                                 //       clk.clk
		.reset              (bridge_0_reset_reset_bridge_in_reset_reset),    // clk_reset.reset
		.src_ready          (router_src_ready),                              //       src.ready
		.src_valid          (router_src_valid),                              //          .valid
		.src_data           (router_src_data),                               //          .data
		.src_channel        (router_src_channel),                            //          .channel
		.src_startofpacket  (router_src_startofpacket),                      //          .startofpacket
		.src_endofpacket    (router_src_endofpacket)                         //          .endofpacket
	);

	jsv_sdram_mm_interconnect_0_router_001 router_001 (
		.sink_ready         (sdram_pll_pll_slave_agent_rp_ready),         //      sink.ready
		.sink_valid         (sdram_pll_pll_slave_agent_rp_valid),         //          .valid
		.sink_data          (sdram_pll_pll_slave_agent_rp_data),          //          .data
		.sink_startofpacket (sdram_pll_pll_slave_agent_rp_startofpacket), //          .startofpacket
		.sink_endofpacket   (sdram_pll_pll_slave_agent_rp_endofpacket),   //          .endofpacket
		.clk                (clk_0_clk_clk),                              //       clk.clk
		.reset              (bridge_0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_001_src_ready),                       //       src.ready
		.src_valid          (router_001_src_valid),                       //          .valid
		.src_data           (router_001_src_data),                        //          .data
		.src_channel        (router_001_src_channel),                     //          .channel
		.src_startofpacket  (router_001_src_startofpacket),               //          .startofpacket
		.src_endofpacket    (router_001_src_endofpacket)                  //          .endofpacket
	);

	jsv_sdram_mm_interconnect_0_router_002 router_002 (
		.sink_ready         (bitmap_sdram_s1_agent_rp_ready),                 //      sink.ready
		.sink_valid         (bitmap_sdram_s1_agent_rp_valid),                 //          .valid
		.sink_data          (bitmap_sdram_s1_agent_rp_data),                  //          .data
		.sink_startofpacket (bitmap_sdram_s1_agent_rp_startofpacket),         //          .startofpacket
		.sink_endofpacket   (bitmap_sdram_s1_agent_rp_endofpacket),           //          .endofpacket
		.clk                (sdram_pll_c0_clk),                               //       clk.clk
		.reset              (bitmap_sdram_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_002_src_ready),                           //       src.ready
		.src_valid          (router_002_src_valid),                           //          .valid
		.src_data           (router_002_src_data),                            //          .data
		.src_channel        (router_002_src_channel),                         //          .channel
		.src_startofpacket  (router_002_src_startofpacket),                   //          .startofpacket
		.src_endofpacket    (router_002_src_endofpacket)                      //          .endofpacket
	);

	jsv_sdram_mm_interconnect_0_cmd_demux cmd_demux (
		.clk                (clk_0_clk_clk),                              //       clk.clk
		.reset              (bridge_0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_src_ready),                           //      sink.ready
		.sink_channel       (router_src_channel),                         //          .channel
		.sink_data          (router_src_data),                            //          .data
		.sink_startofpacket (router_src_startofpacket),                   //          .startofpacket
		.sink_endofpacket   (router_src_endofpacket),                     //          .endofpacket
		.sink_valid         (router_src_valid),                           //          .valid
		.src0_ready         (cmd_demux_src0_ready),                       //      src0.ready
		.src0_valid         (cmd_demux_src0_valid),                       //          .valid
		.src0_data          (cmd_demux_src0_data),                        //          .data
		.src0_channel       (cmd_demux_src0_channel),                     //          .channel
		.src0_startofpacket (cmd_demux_src0_startofpacket),               //          .startofpacket
		.src0_endofpacket   (cmd_demux_src0_endofpacket),                 //          .endofpacket
		.src1_ready         (cmd_demux_src1_ready),                       //      src1.ready
		.src1_valid         (cmd_demux_src1_valid),                       //          .valid
		.src1_data          (cmd_demux_src1_data),                        //          .data
		.src1_channel       (cmd_demux_src1_channel),                     //          .channel
		.src1_startofpacket (cmd_demux_src1_startofpacket),               //          .startofpacket
		.src1_endofpacket   (cmd_demux_src1_endofpacket)                  //          .endofpacket
	);

	jsv_sdram_mm_interconnect_0_cmd_mux cmd_mux (
		.clk                 (clk_0_clk_clk),                              //       clk.clk
		.reset               (bridge_0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (cmd_mux_src_ready),                          //       src.ready
		.src_valid           (cmd_mux_src_valid),                          //          .valid
		.src_data            (cmd_mux_src_data),                           //          .data
		.src_channel         (cmd_mux_src_channel),                        //          .channel
		.src_startofpacket   (cmd_mux_src_startofpacket),                  //          .startofpacket
		.src_endofpacket     (cmd_mux_src_endofpacket),                    //          .endofpacket
		.sink0_ready         (cmd_demux_src0_ready),                       //     sink0.ready
		.sink0_valid         (cmd_demux_src0_valid),                       //          .valid
		.sink0_channel       (cmd_demux_src0_channel),                     //          .channel
		.sink0_data          (cmd_demux_src0_data),                        //          .data
		.sink0_startofpacket (cmd_demux_src0_startofpacket),               //          .startofpacket
		.sink0_endofpacket   (cmd_demux_src0_endofpacket)                  //          .endofpacket
	);

	jsv_sdram_mm_interconnect_0_cmd_mux cmd_mux_001 (
		.clk                 (sdram_pll_c0_clk),                               //       clk.clk
		.reset               (bitmap_sdram_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (cmd_mux_001_src_ready),                          //       src.ready
		.src_valid           (cmd_mux_001_src_valid),                          //          .valid
		.src_data            (cmd_mux_001_src_data),                           //          .data
		.src_channel         (cmd_mux_001_src_channel),                        //          .channel
		.src_startofpacket   (cmd_mux_001_src_startofpacket),                  //          .startofpacket
		.src_endofpacket     (cmd_mux_001_src_endofpacket),                    //          .endofpacket
		.sink0_ready         (crosser_out_ready),                              //     sink0.ready
		.sink0_valid         (crosser_out_valid),                              //          .valid
		.sink0_channel       (crosser_out_channel),                            //          .channel
		.sink0_data          (crosser_out_data),                               //          .data
		.sink0_startofpacket (crosser_out_startofpacket),                      //          .startofpacket
		.sink0_endofpacket   (crosser_out_endofpacket)                         //          .endofpacket
	);

	jsv_sdram_mm_interconnect_0_rsp_demux rsp_demux (
		.clk                (clk_0_clk_clk),                                           //       clk.clk
		.reset              (bridge_0_reset_reset_bridge_in_reset_reset),              // clk_reset.reset
		.sink_ready         (sdram_pll_pll_slave_rsp_width_adapter_src_ready),         //      sink.ready
		.sink_channel       (sdram_pll_pll_slave_rsp_width_adapter_src_channel),       //          .channel
		.sink_data          (sdram_pll_pll_slave_rsp_width_adapter_src_data),          //          .data
		.sink_startofpacket (sdram_pll_pll_slave_rsp_width_adapter_src_startofpacket), //          .startofpacket
		.sink_endofpacket   (sdram_pll_pll_slave_rsp_width_adapter_src_endofpacket),   //          .endofpacket
		.sink_valid         (sdram_pll_pll_slave_rsp_width_adapter_src_valid),         //          .valid
		.src0_ready         (rsp_demux_src0_ready),                                    //      src0.ready
		.src0_valid         (rsp_demux_src0_valid),                                    //          .valid
		.src0_data          (rsp_demux_src0_data),                                     //          .data
		.src0_channel       (rsp_demux_src0_channel),                                  //          .channel
		.src0_startofpacket (rsp_demux_src0_startofpacket),                            //          .startofpacket
		.src0_endofpacket   (rsp_demux_src0_endofpacket)                               //          .endofpacket
	);

	jsv_sdram_mm_interconnect_0_rsp_demux rsp_demux_001 (
		.clk                (sdram_pll_c0_clk),                               //       clk.clk
		.reset              (bitmap_sdram_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_002_src_ready),                           //      sink.ready
		.sink_channel       (router_002_src_channel),                         //          .channel
		.sink_data          (router_002_src_data),                            //          .data
		.sink_startofpacket (router_002_src_startofpacket),                   //          .startofpacket
		.sink_endofpacket   (router_002_src_endofpacket),                     //          .endofpacket
		.sink_valid         (router_002_src_valid),                           //          .valid
		.src0_ready         (rsp_demux_001_src0_ready),                       //      src0.ready
		.src0_valid         (rsp_demux_001_src0_valid),                       //          .valid
		.src0_data          (rsp_demux_001_src0_data),                        //          .data
		.src0_channel       (rsp_demux_001_src0_channel),                     //          .channel
		.src0_startofpacket (rsp_demux_001_src0_startofpacket),               //          .startofpacket
		.src0_endofpacket   (rsp_demux_001_src0_endofpacket)                  //          .endofpacket
	);

	jsv_sdram_mm_interconnect_0_rsp_mux rsp_mux (
		.clk                 (clk_0_clk_clk),                              //       clk.clk
		.reset               (bridge_0_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (rsp_mux_src_ready),                          //       src.ready
		.src_valid           (rsp_mux_src_valid),                          //          .valid
		.src_data            (rsp_mux_src_data),                           //          .data
		.src_channel         (rsp_mux_src_channel),                        //          .channel
		.src_startofpacket   (rsp_mux_src_startofpacket),                  //          .startofpacket
		.src_endofpacket     (rsp_mux_src_endofpacket),                    //          .endofpacket
		.sink0_ready         (rsp_demux_src0_ready),                       //     sink0.ready
		.sink0_valid         (rsp_demux_src0_valid),                       //          .valid
		.sink0_channel       (rsp_demux_src0_channel),                     //          .channel
		.sink0_data          (rsp_demux_src0_data),                        //          .data
		.sink0_startofpacket (rsp_demux_src0_startofpacket),               //          .startofpacket
		.sink0_endofpacket   (rsp_demux_src0_endofpacket),                 //          .endofpacket
		.sink1_ready         (crosser_001_out_ready),                      //     sink1.ready
		.sink1_valid         (crosser_001_out_valid),                      //          .valid
		.sink1_channel       (crosser_001_out_channel),                    //          .channel
		.sink1_data          (crosser_001_out_data),                       //          .data
		.sink1_startofpacket (crosser_001_out_startofpacket),              //          .startofpacket
		.sink1_endofpacket   (crosser_001_out_endofpacket)                 //          .endofpacket
	);

	altera_merlin_width_adapter #(
		.IN_PKT_ADDR_H                 (40),
		.IN_PKT_ADDR_L                 (18),
		.IN_PKT_DATA_H                 (15),
		.IN_PKT_DATA_L                 (0),
		.IN_PKT_BYTEEN_H               (17),
		.IN_PKT_BYTEEN_L               (16),
		.IN_PKT_BYTE_CNT_H             (49),
		.IN_PKT_BYTE_CNT_L             (47),
		.IN_PKT_TRANS_COMPRESSED_READ  (41),
		.IN_PKT_TRANS_WRITE            (43),
		.IN_PKT_BURSTWRAP_H            (50),
		.IN_PKT_BURSTWRAP_L            (50),
		.IN_PKT_BURST_SIZE_H           (53),
		.IN_PKT_BURST_SIZE_L           (51),
		.IN_PKT_RESPONSE_STATUS_H      (71),
		.IN_PKT_RESPONSE_STATUS_L      (70),
		.IN_PKT_TRANS_EXCLUSIVE        (46),
		.IN_PKT_BURST_TYPE_H           (55),
		.IN_PKT_BURST_TYPE_L           (54),
		.IN_PKT_ORI_BURST_SIZE_L       (72),
		.IN_PKT_ORI_BURST_SIZE_H       (74),
		.IN_ST_DATA_W                  (75),
		.OUT_PKT_ADDR_H                (58),
		.OUT_PKT_ADDR_L                (36),
		.OUT_PKT_DATA_H                (31),
		.OUT_PKT_DATA_L                (0),
		.OUT_PKT_BYTEEN_H              (35),
		.OUT_PKT_BYTEEN_L              (32),
		.OUT_PKT_BYTE_CNT_H            (67),
		.OUT_PKT_BYTE_CNT_L            (65),
		.OUT_PKT_TRANS_COMPRESSED_READ (59),
		.OUT_PKT_BURST_SIZE_H          (71),
		.OUT_PKT_BURST_SIZE_L          (69),
		.OUT_PKT_RESPONSE_STATUS_H     (89),
		.OUT_PKT_RESPONSE_STATUS_L     (88),
		.OUT_PKT_TRANS_EXCLUSIVE       (64),
		.OUT_PKT_BURST_TYPE_H          (73),
		.OUT_PKT_BURST_TYPE_L          (72),
		.OUT_PKT_ORI_BURST_SIZE_L      (90),
		.OUT_PKT_ORI_BURST_SIZE_H      (92),
		.OUT_ST_DATA_W                 (93),
		.ST_CHANNEL_W                  (2),
		.OPTIMIZE_FOR_RSP              (0),
		.RESPONSE_PATH                 (0),
		.CONSTANT_BURST_SIZE           (1),
		.PACKING                       (1),
		.ENABLE_ADDRESS_ALIGNMENT      (0)
	) sdram_pll_pll_slave_cmd_width_adapter (
		.clk                  (clk_0_clk_clk),                                           //       clk.clk
		.reset                (bridge_0_reset_reset_bridge_in_reset_reset),              // clk_reset.reset
		.in_valid             (cmd_mux_src_valid),                                       //      sink.valid
		.in_channel           (cmd_mux_src_channel),                                     //          .channel
		.in_startofpacket     (cmd_mux_src_startofpacket),                               //          .startofpacket
		.in_endofpacket       (cmd_mux_src_endofpacket),                                 //          .endofpacket
		.in_ready             (cmd_mux_src_ready),                                       //          .ready
		.in_data              (cmd_mux_src_data),                                        //          .data
		.out_endofpacket      (sdram_pll_pll_slave_cmd_width_adapter_src_endofpacket),   //       src.endofpacket
		.out_data             (sdram_pll_pll_slave_cmd_width_adapter_src_data),          //          .data
		.out_channel          (sdram_pll_pll_slave_cmd_width_adapter_src_channel),       //          .channel
		.out_valid            (sdram_pll_pll_slave_cmd_width_adapter_src_valid),         //          .valid
		.out_ready            (sdram_pll_pll_slave_cmd_width_adapter_src_ready),         //          .ready
		.out_startofpacket    (sdram_pll_pll_slave_cmd_width_adapter_src_startofpacket), //          .startofpacket
		.in_command_size_data (3'b000)                                                   // (terminated)
	);

	altera_merlin_width_adapter #(
		.IN_PKT_ADDR_H                 (58),
		.IN_PKT_ADDR_L                 (36),
		.IN_PKT_DATA_H                 (31),
		.IN_PKT_DATA_L                 (0),
		.IN_PKT_BYTEEN_H               (35),
		.IN_PKT_BYTEEN_L               (32),
		.IN_PKT_BYTE_CNT_H             (67),
		.IN_PKT_BYTE_CNT_L             (65),
		.IN_PKT_TRANS_COMPRESSED_READ  (59),
		.IN_PKT_TRANS_WRITE            (61),
		.IN_PKT_BURSTWRAP_H            (68),
		.IN_PKT_BURSTWRAP_L            (68),
		.IN_PKT_BURST_SIZE_H           (71),
		.IN_PKT_BURST_SIZE_L           (69),
		.IN_PKT_RESPONSE_STATUS_H      (89),
		.IN_PKT_RESPONSE_STATUS_L      (88),
		.IN_PKT_TRANS_EXCLUSIVE        (64),
		.IN_PKT_BURST_TYPE_H           (73),
		.IN_PKT_BURST_TYPE_L           (72),
		.IN_PKT_ORI_BURST_SIZE_L       (90),
		.IN_PKT_ORI_BURST_SIZE_H       (92),
		.IN_ST_DATA_W                  (93),
		.OUT_PKT_ADDR_H                (40),
		.OUT_PKT_ADDR_L                (18),
		.OUT_PKT_DATA_H                (15),
		.OUT_PKT_DATA_L                (0),
		.OUT_PKT_BYTEEN_H              (17),
		.OUT_PKT_BYTEEN_L              (16),
		.OUT_PKT_BYTE_CNT_H            (49),
		.OUT_PKT_BYTE_CNT_L            (47),
		.OUT_PKT_TRANS_COMPRESSED_READ (41),
		.OUT_PKT_BURST_SIZE_H          (53),
		.OUT_PKT_BURST_SIZE_L          (51),
		.OUT_PKT_RESPONSE_STATUS_H     (71),
		.OUT_PKT_RESPONSE_STATUS_L     (70),
		.OUT_PKT_TRANS_EXCLUSIVE       (46),
		.OUT_PKT_BURST_TYPE_H          (55),
		.OUT_PKT_BURST_TYPE_L          (54),
		.OUT_PKT_ORI_BURST_SIZE_L      (72),
		.OUT_PKT_ORI_BURST_SIZE_H      (74),
		.OUT_ST_DATA_W                 (75),
		.ST_CHANNEL_W                  (2),
		.OPTIMIZE_FOR_RSP              (1),
		.RESPONSE_PATH                 (1),
		.CONSTANT_BURST_SIZE           (1),
		.PACKING                       (1),
		.ENABLE_ADDRESS_ALIGNMENT      (0)
	) sdram_pll_pll_slave_rsp_width_adapter (
		.clk                  (clk_0_clk_clk),                                           //       clk.clk
		.reset                (bridge_0_reset_reset_bridge_in_reset_reset),              // clk_reset.reset
		.in_valid             (router_001_src_valid),                                    //      sink.valid
		.in_channel           (router_001_src_channel),                                  //          .channel
		.in_startofpacket     (router_001_src_startofpacket),                            //          .startofpacket
		.in_endofpacket       (router_001_src_endofpacket),                              //          .endofpacket
		.in_ready             (router_001_src_ready),                                    //          .ready
		.in_data              (router_001_src_data),                                     //          .data
		.out_endofpacket      (sdram_pll_pll_slave_rsp_width_adapter_src_endofpacket),   //       src.endofpacket
		.out_data             (sdram_pll_pll_slave_rsp_width_adapter_src_data),          //          .data
		.out_channel          (sdram_pll_pll_slave_rsp_width_adapter_src_channel),       //          .channel
		.out_valid            (sdram_pll_pll_slave_rsp_width_adapter_src_valid),         //          .valid
		.out_ready            (sdram_pll_pll_slave_rsp_width_adapter_src_ready),         //          .ready
		.out_startofpacket    (sdram_pll_pll_slave_rsp_width_adapter_src_startofpacket), //          .startofpacket
		.in_command_size_data (3'b000)                                                   // (terminated)
	);

	altera_avalon_st_handshake_clock_crosser #(
		.DATA_WIDTH          (75),
		.BITS_PER_SYMBOL     (75),
		.USE_PACKETS         (1),
		.USE_CHANNEL         (1),
		.CHANNEL_WIDTH       (2),
		.USE_ERROR           (0),
		.ERROR_WIDTH         (1),
		.VALID_SYNC_DEPTH    (2),
		.READY_SYNC_DEPTH    (2),
		.USE_OUTPUT_PIPELINE (0)
	) crosser (
		.in_clk            (clk_0_clk_clk),                                  //        in_clk.clk
		.in_reset          (bridge_0_reset_reset_bridge_in_reset_reset),     //  in_clk_reset.reset
		.out_clk           (sdram_pll_c0_clk),                               //       out_clk.clk
		.out_reset         (bitmap_sdram_reset_reset_bridge_in_reset_reset), // out_clk_reset.reset
		.in_ready          (cmd_demux_src1_ready),                           //            in.ready
		.in_valid          (cmd_demux_src1_valid),                           //              .valid
		.in_startofpacket  (cmd_demux_src1_startofpacket),                   //              .startofpacket
		.in_endofpacket    (cmd_demux_src1_endofpacket),                     //              .endofpacket
		.in_channel        (cmd_demux_src1_channel),                         //              .channel
		.in_data           (cmd_demux_src1_data),                            //              .data
		.out_ready         (crosser_out_ready),                              //           out.ready
		.out_valid         (crosser_out_valid),                              //              .valid
		.out_startofpacket (crosser_out_startofpacket),                      //              .startofpacket
		.out_endofpacket   (crosser_out_endofpacket),                        //              .endofpacket
		.out_channel       (crosser_out_channel),                            //              .channel
		.out_data          (crosser_out_data),                               //              .data
		.in_empty          (1'b0),                                           //   (terminated)
		.in_error          (1'b0),                                           //   (terminated)
		.out_empty         (),                                               //   (terminated)
		.out_error         ()                                                //   (terminated)
	);

	altera_avalon_st_handshake_clock_crosser #(
		.DATA_WIDTH          (75),
		.BITS_PER_SYMBOL     (75),
		.USE_PACKETS         (1),
		.USE_CHANNEL         (1),
		.CHANNEL_WIDTH       (2),
		.USE_ERROR           (0),
		.ERROR_WIDTH         (1),
		.VALID_SYNC_DEPTH    (2),
		.READY_SYNC_DEPTH    (2),
		.USE_OUTPUT_PIPELINE (0)
	) crosser_001 (
		.in_clk            (sdram_pll_c0_clk),                               //        in_clk.clk
		.in_reset          (bitmap_sdram_reset_reset_bridge_in_reset_reset), //  in_clk_reset.reset
		.out_clk           (clk_0_clk_clk),                                  //       out_clk.clk
		.out_reset         (bridge_0_reset_reset_bridge_in_reset_reset),     // out_clk_reset.reset
		.in_ready          (rsp_demux_001_src0_ready),                       //            in.ready
		.in_valid          (rsp_demux_001_src0_valid),                       //              .valid
		.in_startofpacket  (rsp_demux_001_src0_startofpacket),               //              .startofpacket
		.in_endofpacket    (rsp_demux_001_src0_endofpacket),                 //              .endofpacket
		.in_channel        (rsp_demux_001_src0_channel),                     //              .channel
		.in_data           (rsp_demux_001_src0_data),                        //              .data
		.out_ready         (crosser_001_out_ready),                          //           out.ready
		.out_valid         (crosser_001_out_valid),                          //              .valid
		.out_startofpacket (crosser_001_out_startofpacket),                  //              .startofpacket
		.out_endofpacket   (crosser_001_out_endofpacket),                    //              .endofpacket
		.out_channel       (crosser_001_out_channel),                        //              .channel
		.out_data          (crosser_001_out_data),                           //              .data
		.in_empty          (1'b0),                                           //   (terminated)
		.in_error          (1'b0),                                           //   (terminated)
		.out_empty         (),                                               //   (terminated)
		.out_error         ()                                                //   (terminated)
	);

	jsv_sdram_mm_interconnect_0_avalon_st_adapter #(
		.inBitsPerSymbol (34),
		.inUsePackets    (0),
		.inDataWidth     (34),
		.inChannelWidth  (0),
		.inErrorWidth    (0),
		.inUseEmptyPort  (0),
		.inUseValid      (1),
		.inUseReady      (1),
		.inReadyLatency  (0),
		.outDataWidth    (34),
		.outChannelWidth (0),
		.outErrorWidth   (1),
		.outUseEmptyPort (0),
		.outUseValid     (1),
		.outUseReady     (1),
		.outReadyLatency (0)
	) avalon_st_adapter (
		.in_clk_0_clk   (clk_0_clk_clk),                                  // in_clk_0.clk
		.in_rst_0_reset (bridge_0_reset_reset_bridge_in_reset_reset),     // in_rst_0.reset
		.in_0_data      (sdram_pll_pll_slave_agent_rdata_fifo_src_data),  //     in_0.data
		.in_0_valid     (sdram_pll_pll_slave_agent_rdata_fifo_src_valid), //         .valid
		.in_0_ready     (sdram_pll_pll_slave_agent_rdata_fifo_src_ready), //         .ready
		.out_0_data     (avalon_st_adapter_out_0_data),                   //    out_0.data
		.out_0_valid    (avalon_st_adapter_out_0_valid),                  //         .valid
		.out_0_ready    (avalon_st_adapter_out_0_ready),                  //         .ready
		.out_0_error    (avalon_st_adapter_out_0_error)                   //         .error
	);

	jsv_sdram_mm_interconnect_0_avalon_st_adapter_001 #(
		.inBitsPerSymbol (18),
		.inUsePackets    (0),
		.inDataWidth     (18),
		.inChannelWidth  (0),
		.inErrorWidth    (0),
		.inUseEmptyPort  (0),
		.inUseValid      (1),
		.inUseReady      (1),
		.inReadyLatency  (0),
		.outDataWidth    (18),
		.outChannelWidth (0),
		.outErrorWidth   (1),
		.outUseEmptyPort (0),
		.outUseValid     (1),
		.outUseReady     (1),
		.outReadyLatency (0)
	) avalon_st_adapter_001 (
		.in_clk_0_clk   (sdram_pll_c0_clk),                               // in_clk_0.clk
		.in_rst_0_reset (bitmap_sdram_reset_reset_bridge_in_reset_reset), // in_rst_0.reset
		.in_0_data      (bitmap_sdram_s1_agent_rdata_fifo_out_data),      //     in_0.data
		.in_0_valid     (bitmap_sdram_s1_agent_rdata_fifo_out_valid),     //         .valid
		.in_0_ready     (bitmap_sdram_s1_agent_rdata_fifo_out_ready),     //         .ready
		.out_0_data     (avalon_st_adapter_001_out_0_data),               //    out_0.data
		.out_0_valid    (avalon_st_adapter_001_out_0_valid),              //         .valid
		.out_0_ready    (avalon_st_adapter_001_out_0_ready),              //         .ready
		.out_0_error    (avalon_st_adapter_001_out_0_error)               //         .error
	);

endmodule
